configuration:
  configuration_dir: "git://github.com/pyecharts/pyecharts-mobans!/config"
  template_dir:
  - "git://github.com/moremoban/pypi-mobans?branch=dev&submodule=True!/templates"
  - "git://github.com/pyecharts/pyecharts-mobans!/templates"
  - ".moban.d"
  configuration: pyecharts-extras.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: pyecharts_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - test.sh: test.script.jj2
  - "pyecharts_extras/_version.py": "_version.py.jj2"
  - .gitignore: pyecharts_gitignore.jj2
  - .travis.yml: extras_travis.yml.jj2
  - Pipfile: Pipfile.jj2
  - output: CHANGELOG.rst
    template: CHANGELOG.rst.jj2
  - lint.sh: lint.script.jj2
  - Makefile: Makefile.jj2
  - tests/requirements.txt: tests/requirements.txt.jj2
  - format.sh: format.sh.jj2
